version: "3.3"
services:
  postgres_cadastro:
    container_name: postgres_customer
    image: debezium/example-postgres
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
    ports:
      - "5432:5432"
  jaeguer:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"